global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-microsoft-powershelldsc
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  pull-master:
    parameter_input: dsc-pull-master.json
    template_file: dsc-pull-master.template
  push-master:
    parameter_input: dsc-push-master.json
    template_file: dsc-push-master.template
